name:                Net-GPSD-Server-Fake
version:             0.01
version_from:        lib/Net/GPSD/Server/Fake.pm
abstract:            Provides a Fake GPSD Daemon for watcher mode clients
license:             perl
distribution_type:   module
requires:     
    vars:                          0
    strict:                        0
    IO::Socket:                    0
