# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-GPSD-Server-Fake
version:      0.04
version_from: lib/Net/GPSD/Server/Fake.pm
installdirs:  site
requires:
    IO::Socket:                    0
    strict:                        0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
